nguage:
  - cpp
compiler:
  - g++
before_install:
  - sudo apt-get install libboost-test-dev
  - sudo apt-get install libboost-program-options-dev
  - wget http://waf.googlecode.com/files/waf-1.7.11.tar.bz2
  - tar xjvf waf-1.7.11.tar.bz2
  - cd waf-1.7.11
  - python waf-light configure
  - python waf-light --tools=boost,waf_unit_test
  - chmod 755 waf
  - export PATH=$PWD:$PATH
  - cd ..
  - waf --version
  - git clone https://github.com/nharraud/cpp-coveralls.git
  - sudo pip install ./cpp-coveralls
before_script:
  - waf configure
script:
  - waf build
after_success:
  - ls -laR ./build
  - coveralls --exclude src/test --build-root "./build" -r "./build"
  - ls -laR ./build
  - cd build
  - gcov ./src/main/lib.cpp.1.o
  - ls -laR .

