nguage:
  - cpp
compiler:
  - g++
before_install:
  - sudo apt-get install libboost-test-dev
  - sudo apt-get install libboost-program-options-dev
  - wget http://waf.googlecode.com/files/waf-1.7.11.tar.bz2
  - tar xjvf waf-1.7.11.tar.bz2
  - cd waf-1.7.11
  - python waf-light configure
  - python waf-light --tools=boost,waf_unit_test
  - chmod 755 waf
  - export PATH=$PWD:$PATH
  - cd ..
  - waf --version
before_script:
  - waf configure
script:
  - waf build
